/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.julzz.groups.ui;

import com.julzz.groups.ui.panels.AlgorithmPanel;
import com.julzz.groups.ui.panels.NamePanel;
import com.julzz.groups.ui.panels.ConstraintPanel;
import com.julzz.groups.ui.panels.RelationPanel;
import com.julzz.groups.ui.panels.ResultPanel;
import java.awt.BorderLayout;
import java.util.Arrays;
import java.util.List;


public class Main extends javax.swing.JFrame {

    
    final private List<AbstractPanel> panels = Arrays.asList(
            new NamePanel(), new ConstraintPanel(), new RelationPanel() ,
            new AlgorithmPanel(), new ResultPanel());
    
    private int panelIdx = 0;
    
    private final int startPanel = 0;
    
 
    public Main() {
        initComponents();
        
        Storage.bProblem.addMember(Arrays.asList("Steffen", "Felix", "Manuel", "Frank"));
        Storage.bProblem.setGroupLimits(Arrays.asList(2,2));
        
        
        getContentPane().setLayout(new BorderLayout());
        loadPanel(startPanel);
        updateButtons();
    }
    
     private void removeCurrentPanel() {
        panels.get(panelIdx).save();
        getContentPane().remove(panels.get(panelIdx));
     }
    
    
    private void loadPanel(int idx) {
        panels.get(idx).initialize();
        lblStep.setText(panels.get(idx).getName());
        getContentPane().add(panels.get(idx));
        this.getContentPane().invalidate();
        this.getContentPane().validate();
        this.getContentPane().repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNext = new javax.swing.JToggleButton();
        btnLast = new javax.swing.JToggleButton();
        lblStep = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNext.setText("Weiter");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText("Zurück");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        lblStep.setText("Schritt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(548, Short.MAX_VALUE)
                .addComponent(btnLast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblStep)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void updateButtons() {
        
        if (panelIdx == 0) {
            btnLast.setEnabled(false);
            btnNext.setEnabled(true);
        } else if (panelIdx == panels.size() - 1) { 
            btnNext.setEnabled(false);
            btnLast.setEnabled(true);
        } else {
            btnLast.setEnabled(true);
            btnNext.setEnabled(true);
        }
    }
    
    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        panels.get(panelIdx).save();
        removeCurrentPanel();
        panelIdx++;
        loadPanel(panelIdx);
        updateButtons();
        setFocusableWindowState(false);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        panels.get(panelIdx).save();
        removeCurrentPanel();
        panelIdx--;
        loadPanel(panelIdx);
        updateButtons();
        setFocusableWindowState(false);
    }//GEN-LAST:event_btnLastActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLast;
    private javax.swing.JToggleButton btnNext;
    private javax.swing.JLabel lblStep;
    // End of variables declaration//GEN-END:variables
}
