/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.julzz.groups.ui.panels;

import com.julzz.groups.io.PlainObjectMember;
import com.julzz.groups.ui.AbstractPanel;
import com.julzz.groups.ui.Storage;
import com.julzz.groups.ui.Util;
import java.util.Collection;
import java.util.Set;
import javax.swing.table.DefaultTableModel;


public class ConstraintPanel extends AbstractPanel {

    /**
     * Creates new form NamePanel
     */
    public ConstraintPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblClass = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGroups = new javax.swing.JTable();
        btnInGroup = new javax.swing.JButton();
        btnNotInGroup = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(473, 313));
        setMinimumSize(new java.awt.Dimension(473, 313));
        setName(""); // NOI18N

        tblClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblClass);

        tblGroups.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gruppen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblGroups);

        btnInGroup.setText("unbedingt in einer Gruppe");
        btnInGroup.setToolTipText("");
        btnInGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInGroupActionPerformed(evt);
            }
        });

        btnNotInGroup.setText("auf keinen Fall in einer Gruppe");
        btnNotInGroup.setToolTipText("");
        btnNotInGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotInGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnInGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNotInGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(47, 47, 47)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addComponent(btnInGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnNotInGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInGroupActionPerformed

        Collection<String> group = Util.getSelected(tblClass);
        Storage.bProblem.addForcedGroup(group);
        tblClass.clearSelection();
        updateGroups();
    }//GEN-LAST:event_btnInGroupActionPerformed

    private void btnNotInGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotInGroupActionPerformed
        Collection<String> group = Util.getSelected(tblClass);
        Storage.bProblem.addForbiddenGroup(group);
        tblClass.clearSelection();
        updateGroups();
    }//GEN-LAST:event_btnNotInGroupActionPerformed


    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {                                          
        DefaultTableModel model = (DefaultTableModel) tblGroups.getModel();

        int[] selected = tblGroups.getSelectedRows();

        for (int idx : selected) {
            final boolean forced = (boolean) model.getValueAt(idx, 1);
            final Set<String> group = (Set<String>) model.getValueAt(idx, 2);
            
            if (forced) {
                Storage.bProblem.getForcedGroups().remove(group);
            } else {
                Storage.bProblem.getForbiddenGroups().remove(group);
            }
        }

        updateGroups();

    }               

    @Override
    public void save() {
        super.save(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void initialize() {
        super.initialize(); 
        
        DefaultTableModel model = (DefaultTableModel) tblClass.getModel();
        model.getDataVector().removeAllElements();
        for(PlainObjectMember m : Storage.bProblem.getMembers()) {
            model.addRow(new Object[] {m.getName()});
        }
        
        
    }
    
    

  
    
    private void updateGroups() {
        DefaultTableModel model = (DefaultTableModel) tblGroups.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
           model.removeRow(i);
        }
        for (Set<String> group : Storage.bProblem.getForcedGroups()) {
            final String line = "IN: " + Util.join(group, " | ");
            model.addRow(new Object[] {line, true, group});
        }
        for (Set<String> group : Storage.bProblem.getForbiddenGroups()) {
            final String line = "NICHT IN: " + Util.join(group, " | ");
            model.addRow(new Object[] {line, false, group});
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInGroup;
    private javax.swing.JButton btnNotInGroup;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblClass;
    private javax.swing.JTable tblGroups;
    // End of variables declaration//GEN-END:variables
}
