/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.julzz.groups.ui.panels;

import com.julzz.groups.model.Member;
import com.julzz.groups.ui.AbstractPanel;
import com.julzz.groups.ui.Storage;
import com.julzz.groups.ui.Util;
import java.util.Set;
import javax.swing.table.DefaultTableModel;


public class ConstraintPanel extends AbstractPanel {

    /**
     * Creates new form NamePanel
     */
    public ConstraintPanel() {
        initComponents();
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblGroups = new javax.swing.JTable();
        btnInGroup = new javax.swing.JButton();
        btnNotInGroup = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClass = new com.julzz.groups.ui.components.NameTable();

        setMaximumSize(new java.awt.Dimension(473, 313));
        setMinimumSize(new java.awt.Dimension(473, 313));
        setName(""); // NOI18N

        tblGroups.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gruppen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblGroups);

        btnInGroup.setText("unbedingt in einer Gruppe");
        btnInGroup.setToolTipText("");
        btnInGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInGroupActionPerformed(evt);
            }
        });

        btnNotInGroup.setText("auf keinen Fall in einer Gruppe");
        btnNotInGroup.setToolTipText("");
        btnNotInGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotInGroupActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(tblClass);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNotInGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(209, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(390, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(271, 271, 271)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnInGroup)
                .addGap(8, 8, 8)
                .addComponent(btnNotInGroup)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInGroupActionPerformed

        Set<Member> group = tblClass.getSelected();
        Storage.desc.getInGroup().add(group);
        tblClass.clearSelection();
        update();
    }//GEN-LAST:event_btnInGroupActionPerformed

    private void btnNotInGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotInGroupActionPerformed
        Set<Member> group = tblClass.getSelected();
        Storage.desc.getInGroup().add(group);
        tblClass.clearSelection();
        update();
    }//GEN-LAST:event_btnNotInGroupActionPerformed


    
    private void update() {
        DefaultTableModel model = (DefaultTableModel) tblGroups.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
           model.removeRow(i);
        }
        for (Set<Member> group : Storage.desc.getInGroup()) {
            final String line = "IN: " + Util.join(group, " | ");
            model.addRow(new Object[] {line, true, group});
        }
        for (Set<Member> group : Storage.desc.getNotInGroup()) {
            final String line = "NICHT IN: " + Util.join(group, " | ");
            model.addRow(new Object[] {line, false, group});
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInGroup;
    private javax.swing.JButton btnNotInGroup;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.julzz.groups.ui.components.NameTable tblClass;
    private javax.swing.JTable tblGroups;
    // End of variables declaration//GEN-END:variables
}
