/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.julzz.groups.ui.panels;

import com.julzz.groups.model.Member;
import com.julzz.groups.ui.AbstractPanel;
import com.julzz.groups.ui.Storage;
import java.awt.Color;
import java.awt.Component;
import java.util.Set;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class ConstraintPanel extends AbstractPanel {

    /**
     * Creates new form NamePanel
     */
    public ConstraintPanel() {
        initComponents();

        tblGroups.getColumnModel().getColumn(0).setCellRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col) {
                
                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
                if (row < Storage.desc.getInGroup().size()) l.setBackground(new Color(0, 204, 51));
                else l.setBackground(new Color(255,153,204));

                return l;
            }

        });

        update();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblGroups = new javax.swing.JTable();
        btnInGroup = new javax.swing.JButton();
        btnNotInGroup = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClass = new com.julzz.groups.ui.components.NameTable();
        btnRemove = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(473, 313));
        setMinimumSize(new java.awt.Dimension(473, 313));
        setName(""); // NOI18N

        tblGroups.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gruppen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblGroups);

        btnInGroup.setText("In einer Gruppe");
        btnInGroup.setToolTipText("");
        btnInGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInGroupActionPerformed(evt);
            }
        });

        btnNotInGroup.setText("Nicht in einer Gruppe");
        btnNotInGroup.setToolTipText("");
        btnNotInGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotInGroupActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(tblClass);

        btnRemove.setText("-");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNotInGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(btnRemove)))
                        .addGap(18, 18, 18)
                        .addComponent(btnInGroup)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNotInGroup)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInGroupActionPerformed

        Set<Member> group = tblClass.getSelected();
        Storage.desc.getInGroup().add(group);
        tblClass.clearSelection();
        update();
    }//GEN-LAST:event_btnInGroupActionPerformed

    private void btnNotInGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotInGroupActionPerformed
        Set<Member> group = tblClass.getSelected();
        Storage.desc.getNotInGroup().add(group);
        tblClass.clearSelection();
        update();
    }//GEN-LAST:event_btnNotInGroupActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        
        for(int idx : tblGroups.getSelectedRows()) {
            // is preference
            if (idx < Storage.desc.getInGroup().size()) {
                Storage.desc.getInGroup().remove(tblGroups.getModel().getValueAt(idx, 0));
            }
            else {
                Storage.desc.getNotInGroup().remove(tblGroups.getModel().getValueAt(idx, 0));
            }
        }
        
        update();
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void update() {
        DefaultTableModel model = (DefaultTableModel) tblGroups.getModel();
        model.setRowCount(0);

        for (Set<Member> group : Storage.desc.getInGroup()) {
            model.addRow(new Object[]{group});
        }
        for (Set<Member> group : Storage.desc.getNotInGroup()) {
            model.addRow(new Object[]{group});
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInGroup;
    private javax.swing.JButton btnNotInGroup;
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.julzz.groups.ui.components.NameTable tblClass;
    private javax.swing.JTable tblGroups;
    // End of variables declaration//GEN-END:variables
}
