/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.julzz.groups.ui.panels;

import com.julzz.groups.io.PlainObjectMember;
import com.julzz.groups.model.Member;
import com.julzz.groups.ui.AbstractPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julesy
 */
public class RelationPanel extends AbstractPanel {

    private static PlainObjectMember currentMember = null;

    /**
     * Creates new form RelationPanel
     */
    public RelationPanel() {
        initComponents();

        tblClass.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent event) {

                final int idx = tblClass.getSelectedRow();
                final Member m = tblClass.get(idx);
                tblRelation.update(m);
            }
        });

        tblRelation.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {

            }
        });

        if (tblClass.getRowCount() > 0) {
            tblClass.changeSelection(0, 0, false, false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClass = new com.julzz.groups.ui.components.NameTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRelation = new com.julzz.groups.ui.components.RelationTable();

        jScrollPane1.setViewportView(tblClass);

        tblRelation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblRelationMouseReleased(evt);
            }
        });
        tblRelation.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblRelationPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tblRelation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblRelationPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblRelationPropertyChange


    }//GEN-LAST:event_tblRelationPropertyChange

    private void tblRelationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRelationMouseReleased
        DefaultTableModel model = (DefaultTableModel) tblRelation.getModel();

        for (Member m : tblClass.getSelected()) {

            m.getPreferences().clear();
            m.getRejections().clear();

            for (int i = 0; i < model.getRowCount(); i++) {
                final String sign = (String) model.getValueAt(i, 0);
                final Member other = (Member) model.getValueAt(i, 1);

                if (sign.equals("+")) {
                    m.getPreferences().add(other);

                } else if (sign.equals("-")) {
                    m.getRejections().add(other);
                }
            }
        }
    }//GEN-LAST:event_tblRelationMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.julzz.groups.ui.components.NameTable tblClass;
    private com.julzz.groups.ui.components.RelationTable tblRelation;
    // End of variables declaration//GEN-END:variables
}
