/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.julzz.groups.ui.panels;

import com.julzz.groups.io.PlainObjectMember;
import com.julzz.groups.model.GroupVariable;
import com.julzz.groups.model.Member;
import com.julzz.groups.model.ProblemUtil;
import com.julzz.groups.ui.AbstractPanel;
import com.julzz.groups.ui.Storage;
import com.msu.moo.model.solution.Solution;
import java.util.Collection;
import java.util.Set;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;


public class ResultPane extends AbstractPanel {

    
    private static PlainObjectMember currentMember = null;
    
    /**
     * Creates new form RelationPanel
     */
    public ResultPane() {
        initComponents();
        
      tblSolutions.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                final int idx = tblSolutions.getSelectedRow();
                Solution<GroupVariable> s = Storage.result.get(idx);
                
               
                
                StringBuilder sb = new StringBuilder();
                
               Collection<Set<Member>> groups =  ProblemUtil.getSubgroups(Storage.bProblem.getGroupLimits(), s.getVariable());
       
               int counter = 1;
                for (Set<Member> g : groups) {
                    sb.append("----------------\n");
                    sb.append(String.format("Gruppe %s\n", counter++));
                    sb.append("----------------\n");
                    for(Member m : g) sb.append(m.getName() + "\n");
                }
                
                 txtResult.setText(sb.toString());
                
            }
        });
        
    }
    
  

    @Override
    public void initialize() {
        super.initialize();

        
        if (Storage.result == null) return;
            
        DefaultTableModel model = (DefaultTableModel) tblSolutions.getModel();
        model.getDataVector().removeAllElements();
        
        for (int i = 0; i < Storage.result.size(); i++) {
            model.addRow(new Object[] {String.format("Lösung %s", i+1)});
        }
           
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblSolutions = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();

        tblSolutions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lösungen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSolutions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tblSolutions);

        txtResult.setColumns(20);
        txtResult.setLineWrap(true);
        txtResult.setRows(5);
        jScrollPane4.setViewportView(txtResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblSolutions;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
